#!/bin/bash
set -e
source .venv/bin/activate
pip install Fabric==1.10.1
pip install yattag
pip install python-dateutil
pip install pywebhdfs
pip install git+git://github.com/orenmazor/oozie.py@011cc5985cf39e3ba95a69bafba61c262988d8bb
./camus-shopify/script/update_oozie_schedule
