#!/usr/bin/env python
import os
from fabric.api import env
from fabric.operations import run, put
from environment import targets

env.forward_agent = True
env.host_string = 'management2.ia131.data-chi.shopify.com'
env.user = 'deploy'
app_name = 'camus'
base_path = '/u/apps'

jar_path = os.path.join(os.getcwd(), 'camus-shopify', 'target', 'camus-shopify-0.1.0-shopify1.jar')
gcs_script_path = os.path.join(os.getcwd(), 'camus-shopify', 'script', 'upload_to_gcs.py')
gcs_topics_to_upload = os.path.join(os.getcwd(), 'camus-shopify', 'script', 'upload_topics_to_gcs')

for target in targets:
    target_dir = '/'.join([base_path, target, 'current'])
    run('mkdir -p %s' % target_dir)
    put(jar_path, target_dir)
    put(gcs_script_path, target_dir)
    put(gcs_topics_to_upload, target_dir)

print('Completed upload')
