#!/usr/bin/env python
import os
from fabric.api import env
from fabric.operations import run, put

env.forward_agent = True
env.host_string = 'management2.ia131.data-chi.shopify.com'
env.user = 'deploy'
app_name = 'camus'
base_path = '/u/apps'
targets = ['camus']

jar_path = os.path.join(os.getcwd(), 'camus-shopify', 'target', 'camus-shopify-0.1.0-shopify1.jar')

for target in targets:
    target_dir = '/'.join([base_path, target, 'current'])
    run('mkdir -p %s' % target_dir)
    put(jar_path, target_dir)

print('Completed upload')
